// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfGdIAIYv5mCpjgS8DDTidMKiqeIUjQMA',
    appId: '1:271300130482:web:4b34ea3b77f7d368bafbab',
    messagingSenderId: '271300130482',
    projectId: 'my-capstone-smt6',
    authDomain: 'my-capstone-smt6.firebaseapp.com',
    storageBucket: 'my-capstone-smt6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr1u0OI_CPn8xfHbrZixOj3-5iJSKcxvo',
    appId: '1:271300130482:android:dc4637a571293a8dbafbab',
    messagingSenderId: '271300130482',
    projectId: 'my-capstone-smt6',
    storageBucket: 'my-capstone-smt6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdRA07ARCsyqbwWvrQrUYWIKZDgGtqbjM',
    appId: '1:271300130482:ios:1e31a1c9bf24355abafbab',
    messagingSenderId: '271300130482',
    projectId: 'my-capstone-smt6',
    storageBucket: 'my-capstone-smt6.firebasestorage.app',
    iosBundleId: 'com.example.senjaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdRA07ARCsyqbwWvrQrUYWIKZDgGtqbjM',
    appId: '1:271300130482:ios:1e31a1c9bf24355abafbab',
    messagingSenderId: '271300130482',
    projectId: 'my-capstone-smt6',
    storageBucket: 'my-capstone-smt6.firebasestorage.app',
    iosBundleId: 'com.example.senjaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfGdIAIYv5mCpjgS8DDTidMKiqeIUjQMA',
    appId: '1:271300130482:web:970ffd156ba7ace7bafbab',
    messagingSenderId: '271300130482',
    projectId: 'my-capstone-smt6',
    authDomain: 'my-capstone-smt6.firebaseapp.com',
    storageBucket: 'my-capstone-smt6.firebasestorage.app',
  );
}
